### ISSUE TITLE
请问作者，我在代码中使用了 hparse组件，却出现了一个问题

### ISSUE THREAD

**Issue by 1261466029** [tolizhan/oFrame#2]
$hParseObj = new of_base_com_hParse($html);
        //$html = '<p>&nbsp;原核细胞型微生物包括<input type="button" value="#1" linkageblock="options:1" disabled="">、<input type="button" value="#2" linkageblock="options:2" disabled="">、<input type="button" value="#3" linkageblock="options:3" disabled="">、<input type="button" value="#4" linkageblock="options:4" disabled="">、<input type="button" value="#5" linkageblock="options:5" disabled="">和&nbsp;<input type="button" value="#6" linkageblock="options:6" disabled="">等微生物。</p>';
        var_dump(
            $hParseObj->find('p')->html(),
            $hParseObj->find('input'),
            $hParseObj->find('p input'),
            $hParseObj->find('[linkageblock="options:1"]')->html()
        );

        //echo 
        //1. string(486) "&nbsp;原核细胞型微生物包括<input type="button" value="#1" linkageblock="options:1" disabled="">、<input type="button" value="#2" linkageblock="options:2" disabled="">、<input type="button" value="#3" linkageblock="options:3" disabled="">、<input type="button" value="#4" linkageblock="options:4" disabled="">、<input type="button" value="#5" linkageblock="options:5" disabled="">和&nbsp;<input type="button" value="#6" linkageblock="options:6" disabled="">等微生物。"
        //2. string(0) ""
        //3. string(0) ""
        //4. string(0) ""

        //它无法正确获取到 p标签下的 input
        //我不太清楚这是我使用的场景不太对劲，或者这个hparse 类的find函数 有bug

**Comment by 1261466029** [comment]
抱歉作者，这里是我的理解错误，由于此节点为input，我不应该使用 ->html()来获取该节点内容。

**Comment by tolizhan** [comment]
嗯, 可以用 html(true) 或 attr("outerHTML") 返回 outerHTML 内容^_^
