### ISSUE TITLE
请问作者，对于hParse 多层结构的处理 有一些使用上的问题

### ISSUE THREAD

**Issue by 1261466029** [tolizhan/oFrame#3]
//本来是想要使用hParse来分离它的子节点内容，来分辨是否换行。我尝试使用 _find('\*')->eq()_ 来做递归处理，但是在 _find('\*')_ 的时候我发现它无法返回我预期得到的值。
**//以下是示例代码：**
`$obj= new of_base_com_hParse(`
`            '<p>`
`                <p>`
`                    Jundejheuiwrbghb<br/>iojefohr<br/>Junde`
`                </p>`
`                <p>`
`                    LeeJunde124<br/>3154`
`                </p>`
`                <p>`
`                    Hahaha<br/> enna`
`                </p>`
`            </p>'`
`        );`
`$list= $obj->find('*')->eq();`
`foreach($list as $k=> $v) {`
`           var_dump($v->html(true));`
`}`
**//以下是打印结果：**
`    string(25) "<p>`
`    </p>"`
`    string(84) "<p>`
`    Jundejheuiwrbghb<br>iojefohr<br>Junde`
`   </p>"`
`    string(4) "<br>"`
`    string(0) ""`
`    string(4) "<br>"`
`    string(0) ""`
`    string(66) "<p>`
`    LeeJunde124<br>3154`
`    </p>"`
`    string(4) "<br>"`
`    string(0) ""`
`    string(62) "<p>`
`    Hahaha<br> enna`
`    </p>"`
`    string(4) "<br>"`
`    string(0) ""`
`    string(7) "<p></p>"`

//你会看到打印数据中第一次打印和最后一次打印出现了一个空的p标签。
//而我们用于测试的html中，祖先元素 p 标签没有被打印出来。
//我猜测 句首的 `<p><p>` 被错误解析成 `<p> </p>`
//            句尾的 `</p></p>` 被错误解析成 `<p> </p>`

**Comment by 1261466029** [comment]
而且我们是否可以判断 _find('*')_ 它子节点的的节点类型， 与html中的 _childNodes_ 相似，可以获取到 文本节点，并且 _object_ 中有属性声明他的节点类型。
因为很多时候 我们想要解析的html中不仅仅只有 各种dom标签，还有很多文本节点。
而据我所能看到的，hParse 组件现在应该没有这个功能。

**Comment by tolizhan** [comment]
按照块级元素与内联元素特性与各浏览器解析方式保持一致, 简单的说p标签不能嵌套, 换成div等

**Comment by tolizhan** [comment]
关于 "我们是否可以判断 find('*') 它子节点的的节点类型" 这个问题:
    请使用 `$hParseObj->contents(false);`

**Comment by 1261466029** [comment]
啊，谢谢，原来作者是有考虑的，我没有看到这个函数不好意思。\(\~\_\~
