### ISSUE TITLE
请问作者，对于hParse 我该如何正确使用

### ISSUE THREAD

**Issue by 1261466029** [tolizhan/oFrame#4]
在框架下，我在递归中使用 new of_base_com_hParse($html);时，发现内存泄露的问题。经过调试后定位了问题。
![image](https://user-images.githubusercontent.com/25168736/69206821-c5c98e80-0b88-11ea-8930-a8c984e3e161.png)

of_base_com_hParse类的静态属性parseNode随着不停的实例化子级数量也在增多。
请问我该怎么做才可以正确使用 of_base_com_hParse 致使实例化导致的问题不会发生

**Comment by tolizhan** [comment]
当实例化的对象销毁时会检查节点是否被上下关联来决定销毁, 您可以检查对象是否及时销毁, 同时可以使用节点的操作方式减少对象的创建从而节省内存提升效率, 如: hParse::selectors
当然操作无效, 可以把导致问题的代码整理成单文件可运行的demo发上来, 方便我排查原因
![image](https://user-images.githubusercontent.com/24313888/69207340-610f3380-0b8a-11ea-919c-4449601f61cb.png)

**Comment by 1261466029** [comment]
感谢回复，我可以再次尝试一下。查看这个问题是否可以解决。

**Comment by 1261466029** [comment]
问题已解决。感谢回复
